### ISSUE TITLE
No Example showing on githubpage?

### ISSUE THREAD

**Issue by sroe** [shusain/angular-sh-checkbox#1]
Hi, 
you wrote "See sample in GH-Pages http://shusain.github.io/angular-sh-checkbox" but I can't see a sample showing it in Action, would be nice to have something you could decide online if you use it or not.
Regards

**Comment by shusain** [comment]
Hi will try to add this today or tomorrow for now u can see it in use at http://www.conditsranch.com in the resources page checklist... Sorry for the lack of samples so far

**Comment by shusain** [comment]
Check the link again I added the examples that use the code shown.  Typically I add some extra styles to those classes to avoid the small movements you'll see due to differences in the icon width.
